/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CypressSys;
import CypressSys.Database.PriorityStructure;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import java.util.*;

/**
 *
 * @author Phil
 */
public class CypressGUI extends javax.swing.JFrame {
    private CypressSystem cypressSystem;
    private CardLayout cardLayout;
    private UserAccount currentuser;
    
    /**
     * Creates new form GUI
     */
    public CypressGUI() {
        currentuser = null;
        initComponents();
        cypressSystem = new CypressSystem();
        cardLayout = (CardLayout)(ui1Panel.getLayout());
        cardLayout.addLayoutComponent(welcomePanel,"welcomePanel");
        cardLayout.addLayoutComponent(ui2Panel, "ui2Panel");
        cardLayout.addLayoutComponent(mainPanel,"mainPanel");
        cardLayout.addLayoutComponent(loginPanel,"loginPanel");
        cardLayout.addLayoutComponent(reportPanel,"reportPanel");
        cardLayout.addLayoutComponent(profilePanel,"profilePanel");
        cardLayout.addLayoutComponent(editProfilePanel,"editProfilePanel");
        cardLayout.addLayoutComponent(editPasswordPanel,"editPasswordPanel");
        cardLayout.addLayoutComponent(createAccountPanel,"createAccountPanel");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ui1Panel = new javax.swing.JPanel();
        welcomePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        englishBtn = new javax.swing.JButton();
        frenchBtn = new javax.swing.JButton();
        ui2Panel = new javax.swing.JPanel();
        createBtn = new javax.swing.JButton();
        gologinBtn = new javax.swing.JButton();
        loginPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        loginUsernameField = new javax.swing.JTextField();
        loginPasswordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        loginBackBtn = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        createReportBtn = new javax.swing.JButton();
        viewProfileBtn = new javax.swing.JButton();
        logoutUserBtn = new javax.swing.JButton();
        liveMapBtn = new javax.swing.JButton();
        reportPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        problemComboBox = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        reportAddressField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        submitReportBtn = new javax.swing.JButton();
        backReportPanelBtn = new javax.swing.JButton();
        profilePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        viewProfileBackBtn = new javax.swing.JButton();
        profileNameLabel = new javax.swing.JLabel();
        userReportList = new java.awt.List();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        fullnameProfileLabel = new javax.swing.JLabel();
        telephoneProfileLabel = new javax.swing.JLabel();
        addressProfileLabel = new javax.swing.JLabel();
        emailProfileLabel = new javax.swing.JLabel();
        profileChangeInfoBtn = new javax.swing.JButton();
        profileChangePasswordBtn = new javax.swing.JButton();
        editProfilePanel = new javax.swing.JPanel();
        editNameField = new javax.swing.JTextField();
        editTelephoneField = new javax.swing.JTextField();
        editAddressField = new javax.swing.JTextField();
        editEmailField = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        editProfileBackBtn = new javax.swing.JButton();
        submitEditProfileBtn = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        editPasswordPanel = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        editOldPasswordField = new javax.swing.JPasswordField();
        editNewPasswordField1 = new javax.swing.JPasswordField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        editNewPasswordField2 = new javax.swing.JPasswordField();
        editPasswordBackBtn = new javax.swing.JButton();
        editPasswordSubmitBtn = new javax.swing.JButton();
        createAccountPanel = new javax.swing.JPanel();
        firstnameField = new javax.swing.JTextField();
        telephoneField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        lastnameField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        addressField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        createAccountBtn = new javax.swing.JButton();
        createAccountBackBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("C Y P R E S S");

        ui1Panel.setLayout(new java.awt.CardLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Welcome");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Bienvenue");

        englishBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        englishBtn.setText("English");
        englishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishBtnActionPerformed(evt);
            }
        });

        frenchBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        frenchBtn.setText("Francais");

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(englishBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(frenchBtn)
                .addGap(200, 200, 200))
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(28, 28, 28)
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(englishBtn)
                    .addComponent(frenchBtn))
                .addContainerGap(337, Short.MAX_VALUE))
        );

        ui1Panel.add(welcomePanel, "card6");

        createBtn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        createBtn.setText("Create an Account");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        gologinBtn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        gologinBtn.setText("Log In");
        gologinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gologinBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ui2PanelLayout = new javax.swing.GroupLayout(ui2Panel);
        ui2Panel.setLayout(ui2PanelLayout);
        ui2PanelLayout.setHorizontalGroup(
            ui2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ui2PanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(createBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(gologinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        ui2PanelLayout.setVerticalGroup(
            ui2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ui2PanelLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(ui2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gologinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(270, Short.MAX_VALUE))
        );

        ui1Panel.add(ui2Panel, "card7");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Login");

        jLabel9.setText("Username:");

        jLabel10.setText("Password:");

        loginUsernameField.setToolTipText("Enter your username");

        loginButton.setText("Log In");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        loginBackBtn.setText("Back");
        loginBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(loginUsernameField)
                                .addComponent(loginPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(loginBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)))
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(137, 137, 137)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(loginPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(loginBackBtn))
                .addContainerGap(265, Short.MAX_VALUE))
        );

        ui1Panel.add(loginPanel, "card4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Main Menu");

        createReportBtn.setText("Create a Report");
        createReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createReportBtnActionPerformed(evt);
            }
        });

        viewProfileBtn.setText("View Profile");
        viewProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfileBtnActionPerformed(evt);
            }
        });

        logoutUserBtn.setText("Log Out");
        logoutUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutUserBtnActionPerformed(evt);
            }
        });

        liveMapBtn.setText("See Live Map");
        liveMapBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liveMapBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(0, 338, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createReportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(viewProfileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(liveMapBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logoutUserBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 339, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(51, 51, 51)
                .addComponent(createReportBtn)
                .addGap(18, 18, 18)
                .addComponent(viewProfileBtn)
                .addGap(18, 18, 18)
                .addComponent(liveMapBtn)
                .addGap(18, 18, 18)
                .addComponent(logoutUserBtn)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        ui1Panel.add(mainPanel, "card5");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Submit a Report");

        problemComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Utility Failure", "Potholes", "City Property Vandalism", "Eroded Streets", "Tree Collapse", "Flooded Streets", "Mould and Spore Growth", "Garbage or any Other Road Blocking Objects" }));

        jLabel21.setText("Problem Type:");

        jLabel22.setText("Address (Location):");

        jLabel23.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("350 Victoria Street, Toronto");

        submitReportBtn.setText("Submit");
        submitReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitReportBtnActionPerformed(evt);
            }
        });

        backReportPanelBtn.setText("Back");
        backReportPanelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backReportPanelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reportAddressField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(problemComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 286, Short.MAX_VALUE)
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addComponent(backReportPanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(286, 286, 286))
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(42, 42, 42)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reportAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(problemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backReportPanelBtn)
                    .addComponent(submitReportBtn))
                .addContainerGap(249, Short.MAX_VALUE))
        );

        ui1Panel.add(reportPanel, "card3");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Profile");

        viewProfileBackBtn.setText("Back to Main Menu");
        viewProfileBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfileBackBtnActionPerformed(evt);
            }
        });

        profileNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        profileNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileNameLabel.setText("profileName");

        jLabel24.setText("Report History");

        jLabel25.setText("Full Name:");

        jLabel27.setText("Telephone:");

        jLabel28.setText("Address:");

        jLabel29.setText("Email: ");

        profileChangeInfoBtn.setText("Change Information");
        profileChangeInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileChangeInfoBtnActionPerformed(evt);
            }
        });

        profileChangePasswordBtn.setText("Change Password");
        profileChangePasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileChangePasswordBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profileNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userReportList, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fullnameProfileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(telephoneProfileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addressProfileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailProfileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(profileChangePasswordBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profileChangeInfoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))))
                .addGap(78, 78, 78))
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(viewProfileBackBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profileNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(userReportList, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(162, 162, 162)
                        .addComponent(viewProfileBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(fullnameProfileLabel))
                        .addGap(18, 18, 18)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(telephoneProfileLabel))
                        .addGap(18, 18, 18)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(addressProfileLabel))
                        .addGap(18, 18, 18)
                        .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(emailProfileLabel))
                        .addGap(36, 36, 36)
                        .addComponent(profileChangeInfoBtn)
                        .addGap(18, 18, 18)
                        .addComponent(profileChangePasswordBtn)))
                .addGap(31, 31, 31))
        );

        ui1Panel.add(profilePanel, "card2");

        jLabel26.setText("Full Name");

        jLabel30.setText("Telephone");

        jLabel31.setText("Address");

        jLabel32.setText("Email");

        editProfileBackBtn.setText("Back");
        editProfileBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfileBackBtnActionPerformed(evt);
            }
        });

        submitEditProfileBtn.setText("Submit");
        submitEditProfileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitEditProfileBtnActionPerformed(evt);
            }
        });

        jLabel33.setForeground(new java.awt.Color(153, 153, 153));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("(Leave blank for unchanged)");

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Edit Details");

        javax.swing.GroupLayout editProfilePanelLayout = new javax.swing.GroupLayout(editProfilePanel);
        editProfilePanel.setLayout(editProfilePanelLayout);
        editProfilePanelLayout.setHorizontalGroup(
            editProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProfilePanelLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addGroup(editProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(editProfilePanelLayout.createSequentialGroup()
                        .addGroup(editProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(editProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(editProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(editAddressField)
                            .addComponent(editTelephoneField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editNameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(editEmailField)))
                    .addGroup(editProfilePanelLayout.createSequentialGroup()
                        .addComponent(editProfileBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(submitEditProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(277, Short.MAX_VALUE))
            .addGroup(editProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        editProfilePanelLayout.setVerticalGroup(
            editProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProfilePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(editProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editTelephoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(editProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(editProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addGap(45, 45, 45)
                .addGroup(editProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editProfileBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitEditProfileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        ui1Panel.add(editProfilePanel, "card9");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Edit Password");

        jLabel36.setText("Current Password");

        jLabel37.setText("New Password");

        jLabel38.setText("Confirm New Password");

        editPasswordBackBtn.setText("Back");
        editPasswordBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPasswordBackBtnActionPerformed(evt);
            }
        });

        editPasswordSubmitBtn.setText("Submit");
        editPasswordSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPasswordSubmitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editPasswordPanelLayout = new javax.swing.GroupLayout(editPasswordPanel);
        editPasswordPanel.setLayout(editPasswordPanelLayout);
        editPasswordPanelLayout.setHorizontalGroup(
            editPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
            .addGroup(editPasswordPanelLayout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addGroup(editPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel38)
                    .addComponent(jLabel37)
                    .addComponent(jLabel36)
                    .addComponent(editOldPasswordField)
                    .addComponent(editNewPasswordField1)
                    .addComponent(editNewPasswordField2)
                    .addComponent(editPasswordSubmitBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(editPasswordBackBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        editPasswordPanelLayout.setVerticalGroup(
            editPasswordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPasswordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addGap(84, 84, 84)
                .addComponent(jLabel36)
                .addGap(18, 18, 18)
                .addComponent(editOldPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addComponent(editNewPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel38)
                .addGap(18, 18, 18)
                .addComponent(editNewPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editPasswordSubmitBtn)
                .addGap(18, 18, 18)
                .addComponent(editPasswordBackBtn)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        ui1Panel.add(editPasswordPanel, "card10");

        jLabel11.setText("First");

        jLabel12.setText("Last");

        jLabel13.setText("Username");

        jLabel14.setText("Password");

        jLabel15.setText("Address");

        jLabel16.setText("Telephone Number");

        createAccountBtn.setText("Submit");
        createAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountBtnActionPerformed(evt);
            }
        });

        createAccountBackBtn.setText("Back");
        createAccountBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountBackBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("(6+ Characters)");

        jLabel17.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("(123 Fountain Street, Toronto)");

        jLabel18.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 153, 153));
        jLabel18.setText("(123 456 7890)");

        jLabel19.setText("Email");

        jLabel20.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setText("(JohnSmith@hotmail.com)");

        javax.swing.GroupLayout createAccountPanelLayout = new javax.swing.GroupLayout(createAccountPanel);
        createAccountPanel.setLayout(createAccountPanelLayout);
        createAccountPanelLayout.setHorizontalGroup(
            createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountPanelLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(createAccountPanelLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20))
                    .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addComponent(usernameField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createAccountPanelLayout.createSequentialGroup()
                        .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(firstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastnameField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addGroup(createAccountPanelLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(createAccountPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addComponent(emailField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createAccountPanelLayout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createAccountBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telephoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(createAccountPanelLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18))
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(createAccountPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addGap(250, 250, 250))
        );
        createAccountPanelLayout.setVerticalGroup(
            createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createAccountPanelLayout.createSequentialGroup()
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(createAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telephoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createAccountBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        ui1Panel.add(createAccountPanel, "card8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ui1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ui1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountBtnActionPerformed
        String fullname = "";
        String username = "";
        String password = "";
        String telephone = "";
        String address = "";
        String email = "";
        ArrayList<String> message = new ArrayList<String>();
        
        if(!firstnameField.getText().equals("") && !lastnameField.getText().equals("")){
            fullname = firstnameField.getText() + "" + 
                        lastnameField.getText();
        }else{
            message.add("Full name");
        }
        if(!usernameField.getText().equals("")){
            username = usernameField.getText();
        }else{
            message.add("Username");
        }
        if(!passwordField.getText().equals("")){
            password = passwordField.getText();
        }else{
            message.add("Password");
        }
        if(!addressField.getText().equals("")){
            address = addressField.getText();
        }else{
            message.add("Address");       
        }
        if(!emailField.getText().equals("")){
            email = emailField.getText();
        }else{
            message.add("Email");
        }
        if(!telephoneField.getText().equals("")){
            telephone = telephoneField.getText();
        }else{
            message.add("Telephone");
        }
        if(message.isEmpty()){
            if(password.length() >= 6){
                if(cypressSystem.createUserAccount(
                        fullname, username, password, telephone, address, email
                    )){
                    currentuser = cypressSystem.getUser(username);
                    JOptionPane.showMessageDialog(null, "Account created!");
                    cardLayout.show(ui1Panel, "mainPanel");
                    firstnameField.setText("");
                    lastnameField.setText("");
                    usernameField.setText("");
                    passwordField.setText("");
                    addressField.setText("");
                    emailField.setText("");
                    telephoneField.setText(""); 
                }else{
                    JOptionPane.showMessageDialog(null, "Username taken!");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Password must be at least 6 characters!");
            }
        }else{
            String str = "Missing: ";
            for(int i = 0; i < message.size(); i++){
                str = str + message.get(i);
                if (i != message.size()-1){
                    str = str + ", ";
                }
            }
            JOptionPane.showMessageDialog(null, str);
        }

    }//GEN-LAST:event_createAccountBtnActionPerformed

    private void englishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishBtnActionPerformed
        cardLayout.show(ui1Panel, "ui2Panel");
    }//GEN-LAST:event_englishBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        cardLayout.show(ui1Panel,"createAccountPanel");
    }//GEN-LAST:event_createBtnActionPerformed

    private void gologinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gologinBtnActionPerformed
        cardLayout.show(ui1Panel,"loginPanel");
    }//GEN-LAST:event_gologinBtnActionPerformed

    private void createAccountBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountBackBtnActionPerformed
        firstnameField.setText("");
        lastnameField.setText("");
        usernameField.setText("");
        passwordField.setText("");
        addressField.setText("");
        emailField.setText("");
        telephoneField.setText("");
        cardLayout.show(ui1Panel,"ui2Panel");
    }//GEN-LAST:event_createAccountBackBtnActionPerformed

    private void loginBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBackBtnActionPerformed
        loginUsernameField.setText("");
        loginPasswordField.setText("");
        cardLayout.show(ui1Panel,"ui2Panel");
    }//GEN-LAST:event_loginBackBtnActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        if(loginUsernameField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter username!");
        }else if(loginPasswordField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter password!");
        }else{
            String username = loginUsernameField.getText();
            String password = loginPasswordField.getText();
            boolean valid = cypressSystem.loginUser(new String[]{username, password});
            if (valid == true){
                currentuser = cypressSystem.getUser(username);
                JOptionPane.showMessageDialog(null, "Success!");
                cardLayout.show(ui1Panel, "mainPanel");
                loginUsernameField.setText("");
                loginPasswordField.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Invalid info!");
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void logoutUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutUserBtnActionPerformed
        cypressSystem.logoutUser(currentuser);
        currentuser = null;
        cardLayout.show(ui1Panel,"welcomePanel");
        JOptionPane.showMessageDialog(null, "Logged out!");
    }//GEN-LAST:event_logoutUserBtnActionPerformed

    private void createReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createReportBtnActionPerformed
        cardLayout.show(ui1Panel,"reportPanel");
    }//GEN-LAST:event_createReportBtnActionPerformed

    private void backReportPanelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backReportPanelBtnActionPerformed
        reportAddressField.setText("");
        problemComboBox.setSelectedIndex(0);
        cardLayout.show(ui1Panel,"mainPanel");
    }//GEN-LAST:event_backReportPanelBtnActionPerformed

    private void submitReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitReportBtnActionPerformed
        String address = reportAddressField.getText();
        String concern = (String)problemComboBox.getSelectedItem();
        if (!address.equals("")){
            if (problemComboBox.getSelectedIndex() != 0){
                reportAddressField.setText("");
                problemComboBox.setSelectedIndex(0);
                cypressSystem.submitReport(address,concern,currentuser.getUserName());
                JOptionPane.showMessageDialog(null, "Problem submitted!");
            }else{
                JOptionPane.showMessageDialog(null, "Please input concern!");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please input address!");
        }
    }//GEN-LAST:event_submitReportBtnActionPerformed

    private void viewProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfileBtnActionPerformed
        profileNameLabel.setText(currentuser.getUserName());
        fullnameProfileLabel.setText(currentuser.getFullname());
        addressProfileLabel.setText(currentuser.getAddress());
        telephoneProfileLabel.setText(currentuser.getTeleNum());
        emailProfileLabel.setText(currentuser.getEmail());
        ArrayList<String> history = cypressSystem.getUserReports(currentuser.getUserName());
        if (!history.isEmpty()){
            for (String item : history){
            userReportList.add(item);
            }
        }else{
            userReportList.add("No Reports");
        }
        cardLayout.show(ui1Panel,"profilePanel");
    }//GEN-LAST:event_viewProfileBtnActionPerformed

    private void viewProfileBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfileBackBtnActionPerformed
        userReportList.clear();
        cardLayout.show(ui1Panel,"mainPanel");
    }//GEN-LAST:event_viewProfileBackBtnActionPerformed

    private void editProfileBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfileBackBtnActionPerformed
        editNameField.setText("");
        editAddressField.setText("");
        editTelephoneField.setText("");
        editEmailField.setText("");
        cardLayout.show(ui1Panel,"profilePanel");
    }//GEN-LAST:event_editProfileBackBtnActionPerformed

    private void submitEditProfileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitEditProfileBtnActionPerformed
        JOptionPane.showMessageDialog(null, "Successfully edited account!");
        cypressSystem.modifyUser(
            currentuser.getUserName(), 
            editNameField.getText(), editTelephoneField.getText(), 
            editAddressField.getText(),editEmailField.getText()
        );
        currentuser = cypressSystem.getUser(currentuser.getUserName());
        profileNameLabel.setText(currentuser.getUserName());
        fullnameProfileLabel.setText(currentuser.getFullname());
        addressProfileLabel.setText(currentuser.getAddress());
        telephoneProfileLabel.setText(currentuser.getTeleNum());
        emailProfileLabel.setText(currentuser.getEmail());
        cardLayout.show(ui1Panel,"profilePanel");
        editNameField.setText("");
        editAddressField.setText("");
        editTelephoneField.setText("");
        editEmailField.setText("");
    }//GEN-LAST:event_submitEditProfileBtnActionPerformed

    private void profileChangeInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileChangeInfoBtnActionPerformed
        cardLayout.show(ui1Panel,"editProfilePanel");
    }//GEN-LAST:event_profileChangeInfoBtnActionPerformed

    private void profileChangePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileChangePasswordBtnActionPerformed
        editOldPasswordField.setText("");
        editNewPasswordField1.setText("");
        editNewPasswordField2.setText("");
        cardLayout.show(ui1Panel,"editPasswordPanel");
    }//GEN-LAST:event_profileChangePasswordBtnActionPerformed

    private void editPasswordBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPasswordBackBtnActionPerformed
        cardLayout.show(ui1Panel,"profilePanel");
        editOldPasswordField.setText("");
        editNewPasswordField1.setText("");
        editNewPasswordField2.setText("");
    }//GEN-LAST:event_editPasswordBackBtnActionPerformed

    private void editPasswordSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPasswordSubmitBtnActionPerformed
        String oldpass = editOldPasswordField.getText();
        String newpass1 = editNewPasswordField1.getText();
        String newpass2 = editNewPasswordField2.getText();
        if(!oldpass.equals("") && !newpass1.equals("") && !newpass2.equals("")){
            if(currentuser.getPassword().equals(oldpass)){
                if(!oldpass.equals(newpass1)){
                    System.out.println(oldpass);
                    System.out.println(newpass1);
                    if(newpass1.length() >= 6){
                        if(newpass1.equals(newpass2)){
                            JOptionPane.showMessageDialog(null, "Success! Password has been changed!");   
                            cypressSystem.modifyUserPassword(currentuser.getUserName(), newpass1);
                            currentuser = cypressSystem.getUser(currentuser.getUserName());
                            cardLayout.show(ui1Panel,"profilePanel");
                        }else{
                            editOldPasswordField.setText("");
                            editNewPasswordField1.setText("");
                            editNewPasswordField2.setText("");
                            JOptionPane.showMessageDialog(null, "New passwords do not match!");                    
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Password must be at least 6 characters!");
                    }
                }else{
                    editOldPasswordField.setText("");
                    editNewPasswordField1.setText("");
                    editNewPasswordField2.setText("");
                    JOptionPane.showMessageDialog(null, "New password cannot be same!");
                }
            }else{
                editOldPasswordField.setText("");
                editNewPasswordField1.setText("");
                editNewPasswordField2.setText("");
                JOptionPane.showMessageDialog(null, "Incorrect password!");
            }
        }else{
            editOldPasswordField.setText("");
            editNewPasswordField1.setText("");
            editNewPasswordField2.setText("");
            JOptionPane.showMessageDialog(null, "Please fill out all fields!");
        }
    }//GEN-LAST:event_editPasswordSubmitBtnActionPerformed

    private void liveMapBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liveMapBtnActionPerformed
        ArrayList<PriorityStructure> markers = cypressSystem.getReports();
        ArrayList<String[]> list = new ArrayList<>();
        if (!markers.isEmpty()){
            for(PriorityStructure item: markers){
                String[] str = item.concern.split(" - ");
                String location = str[0];
                String concern = str[1];
                list.add(new String[]{location,concern});
            }
        }
        new LiveMap(list);
    }//GEN-LAST:event_liveMapBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CypressGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CypressGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CypressGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CypressGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CypressGUI().setVisible(true);
            }
        });
        ////////////////////////////////////////////////////////////////////////
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressProfileLabel;
    private javax.swing.JButton backReportPanelBtn;
    private javax.swing.JButton createAccountBackBtn;
    private javax.swing.JButton createAccountBtn;
    private javax.swing.JPanel createAccountPanel;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton createReportBtn;
    private javax.swing.JTextField editAddressField;
    private javax.swing.JTextField editEmailField;
    private javax.swing.JTextField editNameField;
    private javax.swing.JPasswordField editNewPasswordField1;
    private javax.swing.JPasswordField editNewPasswordField2;
    private javax.swing.JPasswordField editOldPasswordField;
    private javax.swing.JButton editPasswordBackBtn;
    private javax.swing.JPanel editPasswordPanel;
    private javax.swing.JButton editPasswordSubmitBtn;
    private javax.swing.JButton editProfileBackBtn;
    private javax.swing.JPanel editProfilePanel;
    private javax.swing.JTextField editTelephoneField;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailProfileLabel;
    private javax.swing.JButton englishBtn;
    private javax.swing.JTextField firstnameField;
    private javax.swing.JButton frenchBtn;
    private javax.swing.JLabel fullnameProfileLabel;
    private javax.swing.JButton gologinBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastnameField;
    private javax.swing.JButton liveMapBtn;
    private javax.swing.JButton loginBackBtn;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField loginPasswordField;
    private javax.swing.JTextField loginUsernameField;
    private javax.swing.JButton logoutUserBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JComboBox<String> problemComboBox;
    private javax.swing.JButton profileChangeInfoBtn;
    private javax.swing.JButton profileChangePasswordBtn;
    private javax.swing.JLabel profileNameLabel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JTextField reportAddressField;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JButton submitEditProfileBtn;
    private javax.swing.JButton submitReportBtn;
    private javax.swing.JTextField telephoneField;
    private javax.swing.JLabel telephoneProfileLabel;
    private javax.swing.JPanel ui1Panel;
    private javax.swing.JPanel ui2Panel;
    private java.awt.List userReportList;
    private javax.swing.JTextField usernameField;
    private javax.swing.JButton viewProfileBackBtn;
    private javax.swing.JButton viewProfileBtn;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
